# Generated by Django 6.0.7 on 2026-07-13 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='portfolio_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
    ]
